### ISSUE TITLE
Secret inside constructor instead of env var

### ISSUE THREAD

**Issue by adelin-b** [yeikiu/ts-crypto-cli#1]
It would be a more flexible and better practice to let the user set the API key and Secret key in the constructor rather than environment variables.

Using process env only to retrieve those keys make it not possible to use dynamic configuration as it would require to change the current env.

**Comment by yeikiu** [comment]
I actually didn't have the use-case of one user with multiple accounts on the same exchange but I agree with your feedback :)

Will be adding a `getExchangeApiClient(key, secret)` method or similar soon!

**Comment by yeikiu** [comment]
Not documented yet, but added dynamic methods to get instances with different API keys/secrets:

- `createKrakenPrivateApiClient`
- `createHitBTCPrivateApiClient`
- `createBinancePrivateApiClient`
